# Generated by Django 4.0 on 2022-03-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_number', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('roles', models.CharField(max_length=200)),
                ('entry_year', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('room_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('member_count', models.IntegerField()),
                ('members', models.ManyToManyField(to='room.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_number', models.IntegerField()),
                ('item_code', models.CharField(max_length=200)),
                ('item_location', models.CharField(max_length=200)),
                ('item_category', models.CharField(max_length=200)),
                ('item_count', models.IntegerField()),
                ('item_notes', models.CharField(max_length=200)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.user')),
            ],
        ),
    ]
